/* 创建管理页面菜单信息表 */
CREATE TABLE IF NOT EXISTS ADMIN_MENU (

  ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  CREATOR_ID BIGINT(20) NOT NULL COMMENT '创建者ID',
  CREATOR_TYPE VARCHAR(100) NOT NULL COMMENT '创建者类型',
  CREATE_TIME DATETIME NOT NULL COMMENT '数据创建时间',
  MODIFIER_ID BIGINT(20) NOT NULL COMMENT '上一次修改者ID',
  MODIFIER_TYPE VARCHAR(100) NOT NULL COMMENT '上一次修改者类型',
  MODIFY_TIME DATETIME NOT NULL COMMENT '上一次修改时间',

  TITLE VARCHAR(10) NOT NULL UNIQUE COMMENT '菜单标题',
  ICON_STYLE VARCHAR(50) COMMENT '图标样式',
  PARENT_ID BIGINT(20) NOT NULL DEFAULT 0 COMMENT '父节点ID',
  PARENT_TITLE VARCHAR(50) COMMENT '父节点名称',
  LINK_URI VARCHAR(100) COMMENT '链接地址',
  SORT_ID INT(5) NOT NULL DEFAULT 0 COMMENT '排序号',
  TYPE VARCHAR(10) NOT NULL COMMENT '菜单类型',
  REFERENCE_TABLE VARCHAR(20) COMMENT '相关表名',

  INDEX(PARENT_ID) COMMENT '父节点ID索引'
) DEFAULT CHARSET = UTF8 ENGINE = INNODB;

/**
  创建APP 会员表
 */
CREATE TABLE IF NOT EXISTS MEMBER (
  ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
  CREATOR_ID BIGINT(20) NOT NULL COMMENT '数据创建者ID',
  CREATOR_TYPE VARCHAR(100) NOT NULL COMMENT '数据创建者类型',
  CREATE_TIME DATETIME NOT NULL COMMENT '数据创建时间',
  MODIFIER_ID BIGINT(20) NOT NULL COMMENT '上一次修改人ID',
  MODIFIER_TYPE VARCHAR(100) NOT NULL COMMENT '上一次修改人类型',
  MODIFY_TIME DATETIME NOT NULL COMMENT '上一次修改时间',

  STORE_ID BIGINT(20) NOT NULL COMMENT '归属门店ID',
  STORE_NAME VARCHAR(20) NOT NULL COMMENT '归属门店名称',
  STORE_CODE VARCHAR(20) NOT NULL COMMENT '归属门店编码',

  MANAGER_ID BIGINT(20) NOT NULL COMMENT '归属客户经理ID',
  MANAGER_NAME VARCHAR(20) NOT NULL COMMENT '归属客户经理姓名',
  MANAGER_MOBILE VARCHAR(11) NOT NULL COMMENT '归属客户经理电话',

  LEVEL_ID BIGINT(20) NOT NULL COMMENT '会员等级ID',

  ROLE_ID BIGINT(20) NOT NULL COMMENT '会员角色ID',
  NAME VARCHAR(20) NOT NULL COMMENT '会员姓名',
  HEAD_IMAGE_URI VARCHAR(100) COMMENT '会员头像路径',
  BIRTHDAY DATETIME COMMENT '会员生日',
  SEX VARCHAR(10) COMMENT '会员性别',
  EFFECTIVE_CONSUMPTION BIGINT(20) COMMENT '有效消费额',
  EFFECTIVE_ORDER_COUNT INT(10) COMMENT '有效单量',
  LAST_LOGIN_TIME DATETIME COMMENT '上一次登录时间',
  REGISTRY_TIME DATETIME NOT NULL COMMENT '注册时间',
  REGISTRY_TYPE VARCHAR(10) NOT NULL COMMENT '注册类型',
  IDENTITY_TYPE VARCHAR(10) NOT NULL COMMENT '身份类型'

) DEFAULT CHARSET = UTF8 ENGINE = INNODB;

/*会员资产信息表*/
CREATE TABLE IF NOT EXISTS MEMBER_WALLET(
  ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
  CREATOR_ID BIGINT(20) NOT NULL COMMENT '数据创建者ID',
  CREATOR_TYPE VARCHAR(100) NOT NULL COMMENT '数据创建者类型',
  CREATE_TIME DATETIME NOT NULL COMMENT '数据创建时间',
  MODIFIER_ID BIGINT(20) NOT NULL COMMENT '上一次修改人ID',
  MODIFIER_TYPE VARCHAR(100) NOT NULL COMMENT '上一次修改人类型',
  MODIFY_TIME DATETIME NOT NULL COMMENT '上一次修改时间',
  MEMBER_ID BIGINT(20) NOT NULL COMMENT '会员主键',
  BALANCE BIGINT(20) NOT NULL COMMENT '会员预存款',
  TREASURE BIGINT(20) NOT NULL COMMENT '会员乐易宝'

) DEFAULT CHARSET = UTF8 ENGINE = INNODB;

/*会员等级信息表*/
CREATE TABLE IF NOT EXISTS MEMBER_LEVEL(
  ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
  CREATOR_ID BIGINT(20) NOT NULL COMMENT '数据创建者ID',
  CREATOR_TYPE VARCHAR(100) NOT NULL COMMENT '数据创建者类型',
  CREATE_TIME DATETIME NOT NULL COMMENT '数据创建时间',
  MODIFIER_ID BIGINT(20) NOT NULL COMMENT '上一次修改人ID',
  MODIFIER_TYPE VARCHAR(100) NOT NULL COMMENT '上一次修改人类型',
  MODIFY_TIME DATETIME NOT NULL COMMENT '上一次修改时间',
  TITLE VARCHAR(20) NOT NULL COMMENT '会员等级名称',
  ICON_URI VARCHAR(100) NOT NULL COMMENT '会员图标地址路径',
  RANK INTEGER(10) COMMENT '会员级别（表示会员等级高低）'

) DEFAULT CHARSET = UTF8 ENGINE = INNODB;

/*会员鉴权信息表*/
CREATE TABLE IF NOT EXISTS MEMBER_AUTH(
  ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
  CREATOR_ID BIGINT(20) NOT NULL COMMENT '数据创建者ID',
  CREATOR_TYPE VARCHAR(100) NOT NULL COMMENT '数据创建者类型',
  CREATE_TIME DATETIME NOT NULL COMMENT '数据创建时间',
  MODIFIER_ID BIGINT(20) NOT NULL COMMENT '上一次修改人ID',
  MODIFIER_TYPE VARCHAR(100) NOT NULL COMMENT '上一次修改人类型',
  MODIFY_TIME DATETIME NOT NULL COMMENT '上一次修改时间',
  MEMBER_ID BIGINT(20) NOT NULL COMMENT '会员主键',
  USER_NAME VARCHAR(20) NOT NULL COMMENT '会员名字',
  PASSWORD VARCHAR(10) NOT NULL COMMENT '会员密码',
  MOBILE VARCHAR (10) NOT NULL COMMENT '会员手机号码',
  EMAIL VARCHAR (20) COMMENT '会员电子邮箱',
  USABLE BIT NOT NULL COMMENT '会员账号是否启用',
  UNUSABLE_END_TIME DATETIME COMMENT '会员账号禁用结束时间'

) DEFAULT CHARSET = UTF8 ENGINE = INNODB;
/*会员特定属性表*/
CREATE TABLE IF NOT EXISTS MEMBER_SPECIFIC_PROPERTY(
  ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
  CREATOR_ID BIGINT(20) NOT NULL COMMENT '数据创建者ID',
  CREATOR_TYPE VARCHAR(100) NOT NULL COMMENT '数据创建者类型',
  CREATE_TIME DATETIME NOT NULL COMMENT '数据创建时间',
  MODIFIER_ID BIGINT(20) NOT NULL COMMENT '上一次修改人ID',
  MODIFIER_TYPE VARCHAR(100) NOT NULL COMMENT '上一次修改人类型',
  MODIFY_TIME DATETIME NOT NULL COMMENT '上一次修改时间',
  MEMBER_ID BIGINT(20) NOT NULL COMMENT '会员主键',
  IS_LOGIN BIT NOT NULL COMMENT '会员当前是否已登录',
  LAST_VISIT_TIME DATETIME COMMENT '上一次操作时间',
  LOGIN_SESSION VARCHAR (50) COMMENT '登录session',
  IS_CASH_ON_DELIVERY BIT NOT NULL COMMENT '是否允许货到付款'

) DEFAULT CHARSET = UTF8 ENGINE = INNODB;

/*会员角色表*/
CREATE TABLE IF NOT EXISTS MEMBER_ROLE (
  ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
  CREATOR_ID BIGINT(20) NOT NULL COMMENT '数据创建者ID',
  CREATOR_TYPE VARCHAR(100) NOT NULL COMMENT '数据创建者类型',
  CREATE_TIME DATETIME NOT NULL COMMENT '数据创建时间',
  MODIFIER_ID BIGINT(20) NOT NULL COMMENT '上一次修改人ID',
  MODIFIER_TYPE VARCHAR(100) NOT NULL COMMENT '上一次修改人类型',
  MODIFY_TIME DATETIME NOT NULL COMMENT '上一次修改时间',
  TITLE VARCHAR(30) NOT NULL COMMENT '角色名称'

) DEFAULT CHARSET = UTF8 ENGINE = INNODB;
